# Generated by Django 6.0 on 2025-12-31 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatreports',
            name='user',
        ),
        migrations.AlterField(
            model_name='threatreports',
            name='csv_file',
            field=models.FileField(max_length=255, upload_to='threat_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])]),
        ),
    ]
