# Generated by Django 6.0 on 2025-12-31 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_threatreports_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatreports',
            name='link',
        ),
    ]
